---
- name: Install flatpak
  become: true
  dnf:
    name: "flatpak"
    state: present
  tags:
    - package
    - flatpak

- name: Enable Flathub repository
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Spotify flatpak
  become: true
  command: flatpak install --assumeyes flathub com.spotify.Client
  tags:
    - flatpak

- name: Install Steam flatpak
  become: true
  command: flatpak install --assumeyes flathub com.valvesoftware.Steam
  tags:
    - flatpak