---
- name: Upgrade the system
  become: true
  dnf:
    name: "*"
    state: latest
  tags:
    - package
    - update
    - dnf

- name: Install RPM Fusion
  become: true
  dnf:
    name: ['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}}.noarch.rpm', 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}}.noarch.rpm']
    state: present
  tags:
    - package
    - dnf
    - rpmfusion

- name: Install base packages
  become: yes
  package:
    name: [git, zsh, hub, neovim, python2-neovim, python3-neovim, toilet, figlet, cowsay]
    state: present
  tags:
    - package
    - install-packages
    - dnf

- name: Install programs
  become: yes
  package:
    name: [thunderbird, lutris]
    state: present
  tags:
    - package
    - install-packages
    - dnf

- name: Install GPU packages
  become: yes
  package:
    name: [xorg-x11-drv-nvidia, akmod-nvidia, xorg-x11-drv-nvidia-cuda, vulkan, xorg-x11-drv-nvidia-cuda-libs, vdpauinfo, libva-vdpau-driver, libva-utils]
    state: present
  tags:
    - packages
    - install-packages
    - desktop
    - dnf
    - nonfree
    - rpmfusion
