---
- name: Change the hostname of the laptop
  become: true
  hostname:
    name: core-laptop
  tags:
    - system
    - hostname

- name: Change the hostname of the desktop workstation
  become: true
  hostname:
    name: core-workstation
  tags:
    - system
    - hostname
    - desktop