---
- name: Change the hostname of the laptop
  become: true
  hostname:
    name: Quasar
  tags:
    - system
    - hostname

- name: Change the hostname of the desktop workstation
  become: true
  hostname:
    name: Zenith
  tags:
    - system
    - hostname
    - desktop