---
- name: Get Information about latests VSCodium release
  uri: 
    url: https://api.github.com/repos/VSCodium/vscodium/releases/latest
    return_content: true
  register: json_reponse

- name: Download latest VSCodium release
  get_url:
    url: "{{ json_reponse.json.assets[4].browser_download_url }}"
    dest: ./temp/vscodium.rpm
  register: url

- name: Installing latest VSCodium release
  become: true
  dnf:
    name: ./temp/vscodium.rpm
    state: present